[package]
name = "fileassetbuilder"
version = "0.3.2"
edition = "2021"

[[bin]]
name = "fileassetbuilder"
path = "src/main.rs"

[dependencies]
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
walkdir = "2.5"
